### ISSUE TITLE
__MACOSX folder breaking Logshark?

### ISSUE THREAD

**Issue by til-jmac** [tableau/Logshark#14] opened 2017-03-06 10:27 UTC
I've used Logshark successfully on several different sets of log files in the past, but I got an error on a recent set. Have read the other similar issue raised on here and confirmed the logs contained both a buildversion.txt and workgroup.yml file. 

There is however a difference in that there is a folder called "__MACOSX" in the zip file. When I remove this, logshark processes correctly. 

Not sure what that folder is doing there though? Thought I'd raise it here in case someone else sees this behaviour.

**Comment by jmangue** [comment] 2017-03-06 20:30
Hi til-jmac,

Thanks for bringing this up.  I am unable to reproduce the issue on my end... I'm wondering if the problem is the contents of the folder, rather than the folder name itself.

To help investigate this, would you be able to email me a copy of the Logshark.log.txt file (found in C:\Program Files\Logshark\Logs" showing the actual error being output?   If it's possible to also send me the contents of the __MACOSX subfolder you're seeing, that would help as well.  My email address is jmangue@tableau.com

Thanks,
-Justin

**Comment by jmangue** [comment] 2017-06-05 17:35
Hi @til-jmac , just wondering if you have any update on this?

Thanks,
-Justin

**Comment by jmangue** [comment] 2017-06-05 18:52
No problem, @til-jmac !  Thanks for following up.  Closing this out :+1:

**Closed by jmangue** 2017-06-05 18:52 UTC
Labels: help wanted
