### ISSUE TITLE
Backgrounder plugin still failing

### ISSUE THREAD

**Issue by Sivivatu** [tableau/Logshark#129] opened 2020-10-22 12:46 UTC
Im running the latest 4.2 release against logs generated from TS 2020.2.3 (Build 2020-6-26) and still generating errors when running the backgrounder logs. This issue was noted as fixed in the latest release.

`Reported by: 'BackgrounderPlugin'. Error: 'Failed to process string as Backgrounder event. This is expected for logs prior to 10.4'`

**Comment by Xantrul** [comment] 2020-10-22 22:08
Hi Paul,

The message you see and the note in the release notes are different things (the note in the release notes is not very specific unfortunately).

The issue we fixed in v4.2 (iirc) is that LogShark wasn't throwing any errors, but produced very little (if any) output with the Backgrounder plugin. This happened because log message format changed and rules Backgrounder plugin had were ignoring the lines they were supposed to parse.

The error message you see simply means that LogShark wasn't able to parse a particular line in Backgrounder logs at all. This happens quite often because Backgrounder sometimes logs two messages on the same line. The message is generally benign and only means that LogShark skipped that one particular line while processing. Unless you see hundreds of those messages in the run summary, feel free to ignore these messages.

**Closed by Xantrul** 2020-10-22 22:08 UTC

**Comment by Sivivatu** [comment] 2020-10-23 20:46
thanks for that clarity but that would mean my problem is different then as the resulting output from my logs is completely empty (there is nothing getting parsed into the backgrounder output at all). I would expect there to be some output as the logs do have content in them.

**Comment by Xantrul** [comment] 2020-10-26 16:36
Plz post a copy of Run Summary here (feel free to mask any parts that you're not comfortable sharing, i.e. log set name)

**Comment by Sivivatu** [comment] 2020-10-30 12:47
What are you looking for in the run summary? This?

`      -----Data Writers Statistics-----
      Lines persisted per data set:
      Apache_ApacheRequests                             : 1901834 lines persisted
      Backgrounder_BackgrounderJobErrors                : 274 lines persisted
      ClusterController_ClusterControllerDiskIoSamples  : 41730 lines persisted
      ClusterController_ClusterControllerErrors         : 53 lines persisted
      ClusterController_ZookeeperFsyncLatencies         : 4 lines persisted
      Config_ConfigEntries                              : 3970 lines persisted
      Config_ProcessTopology                            : 24 lines persisted
      Filestore_Filestore                               : 50599 lines persisted
      Hyper_HyperErrors                                 : 483 lines persisted
      Hyper_HyperQueries                                : 4066960 lines persisted
      Netstat_NetstatEntries                            : 4221 lines persisted
      Postgres_PostgresEvents                           : 242 lines persisted
      ResourceManager_ResourceManagerActions            : 21 lines persisted
      ResourceManager_ResourceManagerCpuSamples         : 234852 lines persisted
      ResourceManager_ResourceManagerMemorySamples      : 234864 lines persisted
      ResourceManager_ResourceManagerThresholds         : 32328 lines persisted
      SearchServer_SearchServerEvents                   : 6888990 lines persisted
      Vizportal_VizportalEvents                         : 658705 lines persisted`

**Comment by Sivivatu** [comment] 2020-10-30 14:55
Scratch this. The issue was I had the old version in the env PATH so each run was using the old version rather than the new version. Run the right version and no problems

**Comment by Xantrul** [comment] 2020-10-30 16:37
Thank you for the update - glad to hear the issue is resolved now!
