### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory w Logshark 3.0.1 and Tableau 2018.2

### ISSUE THREAD

**Issue by jfrappier** [tableau/Logshark#69] opened 2018-10-30 18:11 UTC
Hello,

New to Tableau/Logshark. The directions have mostly worked, however after processing the apache logs I get the following error (i think this is the relevant part - about 1300 lines that look like things are working between these messages):

Initializing Backgrounder plugin..\r\nExecution of Backgrounder plugin started at 5:32 PM..\r\nProcessing Backgrounder job events..\r\nBuilding new extract 'BackgrounderJobs.hyper'..\r\nBuilding new extract 'BackgrounderJobErrors.hyper'..\r\nBuilding new extract 'BackgrounderExtractJobDetails.hyper'..\r\nBuilding new extract 'BackgrounderSubscriptionJobDetails.hyper'..\r\n2307 BackgrounderJob records have been persisted.\r\n4371 BackgrounderJob records have been persisted.\r\n6445 BackgrounderJob records have been persisted.\r\nFinished processing Backgrounder job events!\r\n*** exception in native code ***\r\nSystem.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.\r\n   at com.tableausoftware.hyperextract.Extract.TabExtractClose(Pointer )\r\n",
    "stdout_lines": [
        "Loading Logshark user configuration..",
        "Purging existing MongoDB data..",
        "Starting local MongoDB instance on port 27017..",
        "MongoDB started successfully!",
......lots of messages such as.......
"Completed processing of node1\\backuprestore_0.20182.18.0627.2230523418254334175489\\config\\backuprestore_0.20182.18.0627.2230\\topology.yml (4Kb) [00.10]",
...............................................................
"Apache execution completed! [23.38]",
        "Initializing Backgrounder plugin..",
        "Execution of Backgrounder plugin started at 5:32 PM..",
        "Processing Backgrounder job events..",
        "Building new extract 'BackgrounderJobs.hyper'..",
        "Building new extract 'BackgrounderJobErrors.hyper'..",
        "Building new extract 'BackgrounderExtractJobDetails.hyper'..",
        "Building new extract 'BackgrounderSubscriptionJobDetails.hyper'..",
        "2307 BackgrounderJob records have been persisted.",
        "4371 BackgrounderJob records have been persisted.",
        "6445 BackgrounderJob records have been persisted.",
        "Finished processing Backgrounder job events!",
        "*** exception in native code ***",
        "System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.",
        "   at com.tableausoftware.hyperextract.Extract.TabExtractClose(Pointer )"
    ]
}

Box this is being installed on is Windows 2016
Command used to install:
  Setup_Logshark_v3.0.1.exe /install /quiet

Command used to run Logshark (happens with or without -p)
  logshark C:\Users\bill\downloads\logs.zip -p --startlocalmongo

Logs were generated using tsm as part of nightly backup process

The apache logs/workbook published to the tableau server defined in Logshark.config

**Comment by jfrappier** [comment] 2018-10-30 18:28
eyup - t3. I'll try T2. Thanks!

**Comment by jfrappier** [comment] 2018-10-30 19:06
Works with t2 - no errors. Thanks so much!
![worked](https://user-images.githubusercontent.com/6105793/47743362-47d0d780-dc55-11e8-946d-318de4570fe9.PNG)

**Comment by Ksheetij** [comment] 2018-12-05 15:34
Hello,

I'm also facing a similar issue. In my case the instance type is c5.4xlarge. I don't have the privileges for changing the instance type. 
Will it not be possible to run this on a c5 instance? 
Any alternative solution to get this running?

Thanks,
Ksheetij

**Comment by jfrappier** [comment] 2018-12-05 15:51
Hi Ksheetij,

I've had mixed results changing instance types when tableau was installed. I am running Logshark on a t2.2xl and using Ansible to run the commands remotely to generate and get the logs and copy them to the logshark instance for processing.

A fix for modern instance types would be great.

**Comment by Ksheetij** [comment] 2018-12-06 16:09
Yes, a fix would be great indeed. Thanks for sharing your solution Jonathan. :)

**Comment by Xantrul** [comment] 2018-12-27 01:04
Unfortunately fix for this one is not easy, as there are multiple layers involved and the issue is likely to happen in the layer we don't control: we used IKVM project to transpile Java Hyper Extract API into .NET library and exception is likely to be triggered somewhere in this area.

Brian mentioned in the other thread that we have a new version of the Logshark in the pipeline, and that one is very likely to use one of the supported versions of Extract API. So hopefully this error will not show up in the new version (but if it is - we will have clear path to escalate to the folks working on Hyper)

In the meantime, another workaround for @Ksheetij is to not select plugins which output multiple extracts (Backgrounder, ClusterController, Hyper, ResourceManager, VizqlServer)

**Comment by Xantrul** [comment] 2019-06-12 20:30
There  is a good chance that this is addressed in v3.0.2. Going to close this issue, but if anyone still sees it with the new version, plz let us know

**Closed by Xantrul** 2019-06-12 20:30 UTC
