### ISSUE TITLE
Plug-ins running inconsistently 

### ISSUE THREAD

**Issue by mjfalken** [tableau/Logshark#40] opened 2018-04-10 15:19 UTC
I'm seeing inconsistencies in the plug-in functionality when running Logshark against the same set of logs with the same arguments. For example the first time I ran Logshark against a particular set of logs the Apache plug-in ran properly and a workbook was generated. The second time I ran the same exact command immediately after the first run finished the Apache plug-in failed with the error "Encountered uncaught exception while executing plugin 'Apache': The operation has timed out". I'm seeing similar issues with the Config and Filestore plug-ins while the Backgrounder plug-in never runs successfully.  The logs were generated from Tableau Server 10.5.1 and I'm using Logshark v2.0. Any guidance would be appreciated. Thank you.

**Comment by jmangue** [comment] 2018-04-10 16:09
Hi @mjfalken.. it sounds like what may be happening is that you are experiencing connection timeouts when writing to either MongoDB or Postgres.  This can cause plugins to fail and can cause a gap in data or inconsistent results.  If you analyze your Logshark logs, do you see any timeout-related ERROR events that you can paste here, so that we can narrow down the cause?

**Comment by jmangue** [comment] 2018-05-10 18:18
Yeah, it looks like you are hitting timeouts while opening a connection to Postgres.  I'd recommend troubleshooting your Postgres database to verify that the connection pool isn't exhausted and that you're able to connect manually using PGAdmin from the machine running Logshark.

**Comment by jmangue** [comment] 2018-06-06 21:36
Closing this one out as answered.  Please feel free to reopen if you have additional questions!

**Closed by jmangue** 2018-06-06 21:36 UTC
Labels: help wanted
